name: "Build"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: "bash"

permissions:
  contents: "read"
  packages: "write"

jobs:
  BuildOnMacOSArm64:
    runs-on: "macos-15"
    timeout-minutes: 60

    env:
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/kaito-tokyo/index.json,readwrite"
      VCPKG_ROOT: "${{ github.workspace }}/vcpkg"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Checkout vcpkg repository"
        uses: "actions/checkout@v5"
        with:
          repository: "microsoft/vcpkg"
          path: "${{ env.VCPKG_ROOT }}"

      - name: "Bootstrap vcpkg"
        working-directory: "${{ env.VCPKG_ROOT }}"
        run: "./bootstrap-vcpkg.sh"

      - name: "Install mono"
        run: "brew install mono"

      - name: "Setup NuGet Credentials"
        run: |
          NUGET_PATH="$($VCPKG_ROOT/vcpkg fetch nuget | tail -n1)"
          mono "$NUGET_PATH" sources add \
            -Source "https://nuget.pkg.github.com/kaito-tokyo/index.json" \
            -StorePasswordInClearText \
            -Name "GitHub" \
            -UserName "kaito-tokyo" \
            -Password "${{ secrets.GITHUB_TOKEN }}"
          mono "$NUGET_PATH" setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "https://nuget.pkg.github.com/kaito-tokyo/index.json"

      - name: "Build"
        run: "$VCPKG_ROOT/vcpkg install --triplet arm64-osx-obs"

  BuildOnMacOSX64:
    runs-on: "macos-15"
    timeout-minutes: 60

    env:
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/kaito-tokyo/index.json,readwrite"
      VCPKG_ROOT: "${{ github.workspace }}/vcpkg"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Checkout vcpkg repository"
        uses: "actions/checkout@v5"
        with:
          repository: "microsoft/vcpkg"
          path: "${{ env.VCPKG_ROOT }}"

      - name: "Bootstrap vcpkg"
        working-directory: "${{ env.VCPKG_ROOT }}"
        run: "./bootstrap-vcpkg.sh"

      - name: "Install mono"
        run: "brew install mono"

      - name: "Setup NuGet Credentials"
        run: |
          NUGET_PATH="$($VCPKG_ROOT/vcpkg fetch nuget | tail -n1)"
          mono "$NUGET_PATH" sources add \
            -Source "https://nuget.pkg.github.com/kaito-tokyo/index.json" \
            -StorePasswordInClearText \
            -Name "GitHub" \
            -UserName "kaito-tokyo" \
            -Password "${{ secrets.GITHUB_TOKEN }}"
          mono "$NUGET_PATH" setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "https://nuget.pkg.github.com/kaito-tokyo/index.json"

      - name: "Build"
        run: "$VCPKG_ROOT/vcpkg install --triplet x64-osx-obs"

  BuildOnWindows:
    runs-on: "windows-2022"
    timeout-minutes: 60

    env:
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/kaito-tokyo/index.json,readwrite"
      VCPKG_ROOT: "${{ github.workspace }}/vcpkg"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Checkout vcpkg repository"
        uses: "actions/checkout@v5"
        with:
          repository: "microsoft/vcpkg"
          path: "${{ env.VCPKG_ROOT }}"

      - name: "Bootstrap vcpkg"
        working-directory: "${{ env.VCPKG_ROOT }}"
        shell: "pwsh"
        run: ".\\bootstrap-vcpkg.bat"

      - name: "Setup NuGet Credentials on Windows"
        shell: pwsh
        run: |
          $NUGET_EXE_PATH = & "${{ env.VCPKG_ROOT }}/vcpkg" fetch nuget | Select-Object -Last 1
          
          & $NUGET_EXE_PATH sources add `
            -Source "https://nuget.pkg.github.com/kaito-tokyo/index.json" `
            -StorePasswordInClearText `
            -Name "GitHub" `
            -UserName "kaito-tokyo" `
            -Password "${{ secrets.GITHUB_TOKEN }}"
          & $NUGET_EXE_PATH setapikey "${{ secrets.GITHUB_TOKEN }}" `
            -Source "https://nuget.pkg.github.com/kaito-tokyo/index.json"

      - name: "Build"
        run: "$VCPKG_ROOT/vcpkg install --triplet x64-windows-static-md"

  BuildOnUbuntu:
    runs-on: "ubuntu-24.04"
    timeout-minutes: 60

    env:
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/kaito-tokyo/index.json,readwrite"
      VCPKG_ROOT: "${{ github.workspace }}/vcpkg"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Checkout vcpkg repository"
        uses: "actions/checkout@v5"
        with:
          repository: "microsoft/vcpkg"
          path: "${{ env.VCPKG_ROOT }}"

      - name: "Bootstrap vcpkg"
        working-directory: "${{ env.VCPKG_ROOT }}"
        run: "./bootstrap-vcpkg.sh"
      
      - name: "Install mono"
        run: "sudo apt-get install -y mono-devel"

      - name: "Setup NuGet Credentials"
        run: |
          NUGET_PATH="$($VCPKG_ROOT/vcpkg fetch nuget | tail -n1)"
          mono "$NUGET_PATH" sources add \
            -Source "https://nuget.pkg.github.com/kaito-tokyo/index.json" \
            -StorePasswordInClearText \
            -Name "GitHub" \
            -UserName "kaito-tokyo" \
            -Password "${{ secrets.GITHUB_TOKEN }}"
          mono "$NUGET_PATH" setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "https://nuget.pkg.github.com/kaito-tokyo/index.json"

      - name: "Build"
        run: "$VCPKG_ROOT/vcpkg install --triplet x64-linux"
