name: "Vcpkg Format Manifest"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref == 'refs/heads/main' }}"

defaults:
  run:
    shell: "bash"

permissions:
  contents: "read"

jobs:
  VcpkgFormatManifest:
    runs-on: "ubuntu-24.04"

    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Run gersemi"
        run: |
          $VCPKG_INSTALLATION_ROOT/vcpkg format-manifest vcpkg-overlay-ports/woflssl/wolfssl.json